### ISSUE TITLE
Connection error via ssh tunnel (1.0.8)

### ISSUE THREAD

**Issue by gkostyanikov** [psequel/psequel-issues#10]
Tried identical settings with PG Commander and Psequel. Working in first one and no success in your app. Tested it only with ssh tunnel.

![image](https://cloud.githubusercontent.com/assets/666122/5854614/c6e6873e-a240-11e4-8d15-70331698f071.png)

**Comment by psequel** [comment]
Please try v1.0.9. If it still has this issue, please paste a screenshot of your SSH tab. Thanks!

**Comment by gkostyanikov** [comment]
Problem is still here. SSH'ed to working machine with public key successfully.
![image](https://cloud.githubusercontent.com/assets/666122/5904036/8d55e16e-a596-11e4-9d5b-5a299d32bb05.png)

![image](https://cloud.githubusercontent.com/assets/666122/5904021/731217dc-a596-11e4-82b7-6f14faf9d8d6.png)

**Comment by psequel** [comment]
Thanks for the screenshots. This bug will be fixed in the next release.

**Comment by psequel** [comment]
V1.0.10 should fix this issue. Let me know if it is not the case.

**Comment by itarchmerc** [comment]
I was having this same issue and can confirm it now works in v1.0.10.  Thanks!

**Comment by gkostyanikov** [comment]
Yes! Latest fix works like a charm. Thank you!
