### ISSUE TITLE
Add cmd+/ shortcut to toggle sql comment in query editor.

### ISSUE THREAD

**Issue by bwiggs** [psequel/psequel-issues#12]
It would be really great if I could hit `⌘ + /` to toggle a SQL comment for the current line in the Query Editor. Ideally it would also work for highlighted (even multiline) text.

**Comment by PeterDP** [comment]
Thank you for writing PSequel!  I'd like to toss in my vote for this feature as well.

**Comment by psequel** [comment]
Implemented in v1.2.6.beta.
