### ISSUE TITLE
Horizontal Scrolling Momentum

### ISSUE THREAD

**Issue by bawigga** [psequel/psequel-issues#13]
As mentioned in #4 there seems to be some issues with horizontal scrolling on large tables. It seems if you attempt to perform a horizontal scroll but aren't on a near perfectly horizontal axis (I'm swiping on a trackpad) the scroll is stopped.

**Comment by psequel** [comment]
I was able to reproduce this bug in the past. However, today I found that I'm unable to reproduce it (with my MBP's built-in touchpad or a magic mouse). Maybe a OS X version related problem? I'm using OS X 10.10.2.

**Comment by ivancamilov** [comment]
sometimes I'm able to replicate this for vertical scrolling as well when I have a large enough dataset. I'm using OSX 10.10.3 and have PSequel 1.1.1.

**Comment by ghecho** [comment]
I am able to reproduce this bug in PSequel Version 1 (1.1.1), Yosemite 10.10.3 and a table with 67 columns

**Comment by psequel** [comment]
Fixed in v1.1.2.

**Comment by bawigga** [comment]
This is SO much better. Thank you!
