### ISSUE TITLE
Table Data View - Does not refresh when underlying table structure is changed

### ISSUE THREAD

**Issue by bawigga** [psequel/psequel-issues#15]
I'm currently designing a table and PSequel doesn't seem to update the columns in the Data View until I kill the current window and reconnect to the database. It would be great if the Data View would update itself with the latest columns in the database.

**Comment by psequel** [comment]
Click the refresh button in the sidebar to refresh the table list and table metadata. It's not very efficient for PSequel to keep refreshing table schemas in the background.

**Comment by bawigga** [comment]
OK, I didn't see that button. Thanks for pointing it out.
