### ISSUE TITLE
Show Total Row Count in the status bar

### ISSUE THREAD

**Issue by bawigga** [psequel/psequel-issues#16]
Currently, PSequel shows the current number of rows being displayed in the Data view. 

![screenshot 2015-02-05 16 32 36](https://cloud.githubusercontent.com/assets/7358/6070718/aabf94d2-ad54-11e4-8587-15156dc38209.png)

It would be nice if it also showed the total count of rows for the current table.

**Comment by psequel** [comment]
In order to get the *accurate* row count of a table, a full table scan is needed. That would be problematic for a large table. Any suggestions how this feature should be implemented?

**Comment by bawigga** [comment]
I've been doing some reading up on this and it seems you either have to rely on the full table scan to get an accurate count, or you can get an approximate count which is much more performant, but could be stale if VACUUM hasn't been run in a while.

What if you used the approximate to pre-check the table row count? If it's a lower number then go ahead and perform a count(*), otherwise return the approximate number. The initial check could be done the first time the Data view is loaded and cached for the PSequel session.

In the view, there could be an indicator for approximate vs accurate row count:

"1,337 records"
"~100,000,000,000 records"

Here's a screenshot from Sequel Pro of how they show this:

![screenshot 2015-02-07 22 17 13](https://cloud.githubusercontent.com/assets/7358/6095230/25fc3b6e-af17-11e4-8fca-222c53bd7122.png)


See here for more info: https://wiki.postgresql.org/wiki/Slow_Counting

**Comment by psequel** [comment]
Good idea. Will implement this feature.

**Comment by psequel** [comment]
Implemented in v1.0.11
