### ISSUE TITLE
Case-Insensitive Search for Tables

### ISSUE THREAD

**Issue by suxonoff** [psequel/psequel-issues#19]
In PostgreSQL all unquoted identifiers are transformed to lower_case, however, it is possible to create table or column name in any case using quotation: CREATE TABLE "STATUS" { ... }, SELECT * FROM STATUS <-- syntax error because it equals to "status". Currently, you should be aware of it when filtering tables in PSequel, but I think such "quick search" feature  should ignore case completely (you can do this by caching table names on client in lower case and lower the case of input from GUI)

**Comment by psequel** [comment]
Implemented in v1.0.11
