### ISSUE TITLE
Connecting with postgres: URL discloses password

### ISSUE THREAD

**Issue by codepope** [psequel/psequel-issues#28]
When you connect using a postgres: URL with the username and password embedded in it, that username and password are displayed in the titlebar of the window while connected making it easy to shoulder surf.

Suggest either redacting the password from the displayed URL or adding option to save the password on the keychain with a URL login and adding it to the URL when needed for a connection.

**Comment by psequel** [comment]
In v1.0.11, URLs are not displayed in the title bar.
