### ISSUE TITLE
Sidebar text doesn't scale on start

### ISSUE THREAD

**Issue by patricks** [psequel/psequel-issues#33]
If I start the app all titles are cut, but if a resize the sidebar the text resizes fine. Maybe you can fix this sometime. I have attached a screenshot to show you the problem.

![screen shot 2015-04-02 at 14 36 18](https://cloud.githubusercontent.com/assets/132167/6964057/fe314efe-d945-11e4-909f-0041594903dd.png)

**Comment by bawigga** [comment]
I'm seeing the same issue with the bookmarks sidebar. However, when I resize the sidebar, it doesn't fix it.

![screenshot 2015-05-15 16 28 13](https://cloud.githubusercontent.com/assets/7358/7662235/b7bf10ea-fb1f-11e4-8cd0-f0ac122075e1.png)

**Comment by psequel** [comment]
Fixed in v1.1.2.
