### ISSUE TITLE
Are you going to keep the project private?

### ISSUE THREAD

**Issue by diegotdai** [psequel/psequel-issues#36]
I think with community support, the project might evolve faster.

**Comment by bawigga** [comment]
Others have shown interest in providing support as well. See #22

**Comment by JHKennedy4** [comment]
I'd really love to take a crack at the horizontal scroll momentum issue...

**Comment by rdp** [comment]
+1 from me

**Comment by jgonera** [comment]
Is there any reason why you're keeping it private? Are you planning on making it a commercial app in future?

**Comment by psequel** [comment]
> Are you planning on making it a commercial app in future?

Possibly yes.
