### ISSUE TITLE
size column width accordingly to the size of the column name 

### ISSUE THREAD

**Issue by M4urice** [psequel/psequel-issues#38]
The column names should be resized if the window is large enough (or even always). So `integer_value` instead of `int...lue` as shown here:

![screenshot 2015-04-26 15 08 54](https://cloud.githubusercontent.com/assets/1615089/7337331/bc5485de-ec26-11e4-8586-dd60fa9a23ec.png)

**Comment by bawigga** [comment]
+1 on this. 

I find myself constantly doing this after running arbitrary queries.

**Comment by psequel** [comment]
Fixed in v1.1.2.
