### ISSUE TITLE
View column types?

### ISSUE THREAD

**Issue by bronson** [psequel/psequel-issues#4]
Is there a way to see the schema of a table?  Right now, if I scroll a loooong way horizontally, I can see all the column names.  No types, indices, or anything else though.  Am I missing something?

Also, is it intentional that scrolling horizontally feels so dead?  Scrolling vertically has momentum, scrolling horizontally doesn't.  Makes it take a lot of swipes to move through a table.

Thanks!

**Comment by psequel** [comment]
Table structure view is available in v1.2.0.
