### ISSUE TITLE
Export the full result of a Query

### ISSUE THREAD

**Issue by ivancamilov** [psequel/psequel-issues#42]
Right now, the only way to export data I've been able to find is selecting some rows and `right click->Export to CSV`.

However, this is a little annoying for query results that have more than 25 rows. I'd suggest adding a button that allows us to export all the results of a query.

**Comment by bawigga** [comment]
+1

**Comment by psequel** [comment]
You could set the page size to be "unlimited" and then select all rows.

**Comment by ivancamilov** [comment]
You're right, thanks for pointing that out.

**Comment by dannyfreed** [comment]
I only see "Copy to CSV" when I right-click now. Did export functionality get removed?

**Comment by psequel** [comment]
Command + A to select all rows and then copy
