### ISSUE TITLE
going between different DB's isn't easy.

### ISSUE THREAD

**Issue by rdp** [psequel/psequel-issues#43]
Hello.  Today if you first open up one DB connection, then want to "switch" to another one (I'm OK with the fact that I can only open one at a time, but sometimes want to move to another DB), here's what I would anticipate:

If I close ("red X") my current open connection, it would go back and show me the list of connections so I can choose another.

Today it just goes back to "nothing" (no windows open, program still running).  There doesn't even appear to be a menu option "establish new connection" so I basically have to exit out completely then restart the app to switch databases.  Which doesn't seem ideal.  If it were open source I'd try and look at it myself (though not knowing Swift, it's not immediately clear if I would be able)...
Cheers!

**Comment by psequel** [comment]
Please use cmd + N to open a new window.
