### ISSUE TITLE
Warning on quitting app or closing connection window

### ISSUE THREAD

**Issue by jayshepherd** [psequel/psequel-issues#44]
First of all, **THANK YOU** for this app. I'm recently converting a bit project from MySQL to Postgres and the only negative I have re: Postgres is the lack of quality tools. You are on the right track!

---

One of my biggest complaints re: Sequel Pro is that it is 1) very easy to lose your work, 2) Confusing (IMO) to save sessions/connections, etc., and 3) doesn't autosave workspace.

*Ease of losing work*: 
I don't know about others, but when I'm heads down working through various SQL statements I often have lots of differing ones and notes to myself embedded on the SQL editor. Losing these because I accidentally CMD+W or CMD+Q with Sequel Pro was maddening.

*Autosave*:
Years ago, I used a tool with SQL Server on windows (can't remember the name) but it auto-saved everything in files so that you could always go back and look at work you've done but forgot to specifically save. So, you could save under a specific name, but even if you didn't it saved it for you.

**Comment by psequel** [comment]
To make it harder to quit an app accidentally, you could change the shortcuts in System Preferences -> Keyboard -> Shortcuts -> App Shortcuts.

The "autosave" feature might be implemented in future releases.

**Comment by jayshepherd** [comment]
@psequel Thanks for the tip re: App Shortcuts. Works well.

**Comment by psequel** [comment]
Closing this issue for now. For the "autosave" feature, if you (or anyone else) think it's important, please open a separate issue.
