### ISSUE TITLE
connection name is truncated "too early"

### ISSUE THREAD

**Issue by rdp** [psequel/psequel-issues#46]
On the initial "select your connection" screen, if I name anything longer than the word "New Connection" it appears to truncate the name with ellipses, even when there is adequate screen real estate to display it.
Thanks! (as a small side note, might be nice to have a google group for the project, and also might be nice to list on the psequel website "which version" is the latest, so we can know if we're out of date already or not, before reporting bugs).
Cheers!
![screen shot 2015-06-19 at 11 37 44 am](https://cloud.githubusercontent.com/assets/12496/8259171/ce6cb81a-1677-11e5-81b6-78d1144e2216.png)

**Comment by rdp** [comment]
It shows this way at startup.  Interestingly, if you decrease the size of the "Connections" pane, then bring it back to its initial size, the truncating isn't there anymore, FWIW.

**Comment by psequel** [comment]
Fixed in v1.1.2.

**Comment by rdp** [comment]
Awesome, working well now.
