### ISSUE TITLE
Very long queries

### ISSUE THREAD

**Issue by jorisgillis** [psequel/psequel-issues#47]
PSequel becomes extremely slow when a big query (> 20.000 characters on a couple of lines; computer-generated, loaded for debugging purposes) is pasted into the query window.

**Comment by psequel** [comment]
Because it's expensive to parse a big query in order to do syntax highlighting. I'll add an option for disabling syntax highlighting.

**Comment by psequel** [comment]
An option for disabling syntax highlighting is added in v1.2.0. You would want to disable "auto-uppercase keywords" as well for a large query so that PSequel doesn't need to parse that query.

**Comment by jorisgillis** [comment]
Great. Thanks!
