### ISSUE TITLE
Persistent Store Migration Failed

### ISSUE THREAD

**Issue by bawigga** [psequel/psequel-issues#49]
I get this when starting the app.

![bfyan0nkkrtrk-6b0wijhuaz0ricynxj-o_lecxp3ma](https://cloud.githubusercontent.com/assets/7358/8525407/49832006-23c6-11e5-89d6-01671da67a2a.png)

Clicking ok seems to take me to the app just fine.

**Comment by psequel** [comment]
This usually happens when Core Data migration is handled incorrectly. However, the last time the data model changed was v1.0.8. Which versions are you upgrading from and to?

**Comment by bawigga** [comment]
Ya, this could have been an old version. I had installed a version from your site as well as a version with homebrew. I'm guessing one of those was out of date. Haven't been able to reproduce after I deleted the old version.
