### ISSUE TITLE
Previous Query Errors being reported

### ISSUE THREAD

**Issue by bwiggs** [psequel/psequel-issues#57]
I'm currently developing a large report query. I'm noticing that every once in a while I'm getting server errors from previous queries. 

PSequel Version 1 (1.2.2.beta)

Screencast:
![psequel-wrong-server-error](https://cloud.githubusercontent.com/assets/7358/8993027/e0ce41e8-36c7-11e5-9eb4-2187e6351575.gif)

Before the query you can see in the screencast, I was working on a query that used an id lookup of the number you can see in the error alert. 

I've seen this happen a few times now, but can't nail down any reproduction steps. Maybe something to do with using cmd+[ to cycle through old queries? I'll report back more if something comes to light.

**Comment by bawigga** [comment]
I verified that PSequel is sending through the correct query to postgres. See screencast with postgres logging output.

![psequel-wrong-server-error-2](https://cloud.githubusercontent.com/assets/7358/8993190/0f9e79ec-36c9-11e5-8498-77cf19b40303.gif)

**Comment by psequel** [comment]
I guess there might be a race condition as queries run in a background thread. The error you saw might come from a previous invalid query.

**Comment by bawigga** [comment]
Quick update - this happening very consistently for me.

**Comment by psequel** [comment]
Quick update - there seems to be a bug in the driver itself.

Working on a fix. This will take a while.

**Comment by psequel** [comment]
Fixed in v1.2.5.beta
