### ISSUE TITLE
ability to "run highlighted query"

### ISSUE THREAD

**Issue by rdp** [psequel/psequel-issues#59]
Hello.
As part of debugging queries, sometimes I'll want to run "half" of a query, for instance

```
select * from tablename
where x = y;

and timestamp = z;
```

just running the first half of it, to debug the query.  In most editors this is accomplished by highlighting a portion then click "run query" and it runs just the highlighted portion.  Might be nice to do the same here. Cheers!

**Comment by bawigga** [comment]
Dup: https://github.com/psequel/psequel-issues/issues/14

**Comment by rdp** [comment]
closing as dupe
