### ISSUE TITLE
Feature Request: Validation and Error Logging

### ISSUE THREAD

**Issue by daneb** [psequel/psequel-issues#6]
This looks like something with a lot of potential thank you.
Unfortunately I am using Yosemite but for some reason I cannot "connect" to any of my databases.

There doesn't seem to be any validation in the "Connect" button, nor is there any error reporting telling me if something is failing etc. If I switch between a valid password and invalid, I get no feedback.

Thanks
Dane

**Comment by psequel** [comment]
You are right there is no validation at this moment. But if you input a wrong password and try to connect, you should get an alert telling you that your password is incorrect, no?

**Comment by daneb** [comment]
Unfortunately I get no feedback at all, and no matter the amount of times I click "Connect", the application seems unaffected.
I moved the file into Application, tried to grant it control in Privacy - still nothing

**Comment by psequel** [comment]
Did you create a new connection by clicking the `+` button before entering details for that connection? Please see [this comment](2#issuecomment-68899453).

**Comment by daneb** [comment]
No I didn't - in fact I didn't even see it there ;)
Apologies - that does indicate however that "it's not necessarily
intuitive". None the less, appreciate the software and the response, so
thank you.
Will give it a shot!



On Tue, Jan 6, 2015 at 7:38 PM, PSequel <notifications@github.com> wrote:

> Did you create a new connection by clicking the + button before entering
> details for that connection? Please see this comment
> <http://2#issuecomment-68899453>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psequel/psequel-issues/issues/6#issuecomment-68900695>
> .
>



-- 

±± http://www.codedtrue.com ±±

**Comment by psequel** [comment]
As I mentioned in the other issue, this is a regression that will be fixed in the next release. Stay tuned! Close this issue for now.
