### ISSUE TITLE
have ability to display column types

### ISSUE THREAD

**Issue by rdp** [psequel/psequel-issues#62]
Today it seems you cannot see what "type" a column is, within a table.
Suggestion/feature request: add a right click on a table " -> show creation sql" and if they select it, it spits out the table creation sql like 

```
-- Table: tape

-- DROP TABLE tape;

CREATE TABLE tape
(
  tapeid character(6) NOT NULL,
  ...
  CONSTRAINT tapenamecheck CHECK (tapeid ~ '^[0-9A-Z]{6}$'::text)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE tape
  OWNER TO tape;


-- Index: streamrefidx

-- DROP INDEX streamrefidx;

CREATE INDEX myindex
  ON tape
  USING btree
  (tapeid);

```

That type of thing.  Possibly also display the indexes as well, doesn't seem possible to see them currently either.  Cheers!

**Comment by psequel** [comment]
The latest beta release has a "Structure" tab that shows column types and indexes.

**Comment by rdp** [comment]
Nice (might be nice to add an "SQL" pane for recreating the table elsewhere) but works well. Might be also nice to add a note that download "other versions" includes betas (on the website--at first glance, it sounds like it's just for older versions :)

**Comment by psequel** [comment]
The homepage of the website has a link for downloading other versions. Also, you could turn on "allow updating to beta versions" in Preferences.
