### ISSUE TITLE
Sidebar collapses by default in El Capitan

### ISSUE THREAD

**Issue by kenips** [psequel/psequel-issues#63]
In El Capitan, the sidebar collapses once connected to the DB and you have to drag to resize it every time after connecting. I thought this was an El Capitan bug but now that it's out of beta perhaps this requires app changes? Running PSequel 1.2.5.beta

![psequel](https://cloud.githubusercontent.com/assets/794915/10078749/3dcb0e9a-62b4-11e5-8231-f04d4e2c77b6.png)

**Comment by patricks** [comment]
+1

**Comment by UnderpantsGnome** [comment]
The Query panel also defaults to completely closed.

![screenshot 2015-10-09 17 06 36](https://cloud.githubusercontent.com/assets/17270/10407473/491f0bc0-6ea8-11e5-85a0-f76f536479d5.png)

**Comment by psequel** [comment]
Fixed in v1.2.6.beta.

**Comment by patricks** [comment]
I have installed 1.2.6 beta now. It looks like the query panel is fixed, but the sidebar has the same problem on my machine.

**Comment by psequel** [comment]
Yeah, in El Capitan, somehow the left pane has a very small default width. But once you resize it, PSequel will remember its width.
