### ISSUE TITLE
List of tables is white on grey

### ISSUE THREAD

**Issue by codepope** [psequel/psequel-issues#8]
The list of tables is white on grey here which is really hard to read...

![screenshot 2015-01-09 09 44 59](https://cloud.githubusercontent.com/assets/72684/5677900/45162bbc-97e4-11e4-9c31-f4da5255c137.png)

**Comment by psequel** [comment]
Could you tell me your OS X version and PSequel version? Did you turn on "Invert colors" in "System Preferences" -> "Accessibility"?

**Comment by codepope** [comment]
OS X Yosemite 10.10.2 pre-release, the latest prequel off the auto update and no, I haven't flipped invert colours.

**Comment by psequel** [comment]
I'll work on a fix when 10.10.2 becomes final.

**Comment by erictrinh** [comment]
Also getting this bug in 10.10.2

**Comment by bawigga** [comment]
Same here, 10.10.2.

**Comment by brunoar89** [comment]
Same here, 10.10.2.

**Comment by psequel** [comment]
Fixed in v1.0.10.
