### ISSUE TITLE
keyboard shortcut to execute query

### ISSUE THREAD

**Issue by schmeisers** [psequel/psequel-issues#9]
A small enhancement request: ⌘ + return as a shortcut to execute a query.

**Comment by psequel** [comment]
The shortcut to execute query is ⌘ + R currently (the same shortcut for refreshing table data). You think ⌘ + return is better?

**Comment by schmeisers** [comment]
Good to know about ⌘ + R.  I didn't notice the tool-tip over the query button.

I prefer ⌘ + return, but that is just personal preference and muscle memory from other applications like Base (for sqlite) and email.

**Comment by psequel** [comment]
Cool. Maybe I'll make shortcuts configurable in the future but that's not a high priority item in my todo list. Close this issue for now.
